const express = require('express');
const app = express();
//define a port on which it should listen too
const port = 3000;
// generated by ChatGPT
const tasks = [
    {
        id: 1,
        title: "Complete project",
        description: "Finish coding the project and submit it",
        assignedTo: "John",
        status: "In Progress"
    },
    {
        id: 2,
        title: "Review feedback",
        description: "Review and incorporate feedback from the team",
        assignedTo: "Emily",
        status: "Pending"
    },
    {
        id: 3,
        title: "Prepare presentation",
        description: "Create slides and rehearse the presentation",
        assignedTo: "Mike",
        status: "Not Started"
    }
];
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
//----------------------------------------------//
app.get('/tasks', (request, response) => {
    response.setHeader('Content-Type', 'application/json');
    response.status(200).json(tasks);
}); //todo: output of the id too??
app.post('/tasks', (request, response) => {
    const newTask = request.body;
    tasks.push(newTask);
    response.setHeader('Content-Type', 'application/json');
    response.status(201).json(newTask);
});

app.listen(port, () => {
    console.log('Listening on Port: ', port)
});